-- Insert categories
INSERT INTO public.categories (name, description) VALUES
('Cleansers', 'Gentle cleansing products for all skin types'),
('Moisturizers', 'Hydrating creams and lotions'),
('Treatments', 'Specialized treatment products'),
('Masks', 'Face masks for various skin concerns'),
('Serums', 'Concentrated treatment serums'),
('Professional', 'Professional mesotherapy products')
ON CONFLICT (name) DO NOTHING;

-- Insert ABS Beauty Pharm products
INSERT INTO public.products (name, description, volume, active_ingredients, effects, directions, price, category) VALUES
('CLEAR:UP EMULSION', 'Light cleansing emulsion with a velvety texture for the removal of oil-soluble contaminants and make-up', '250 mL', 'squalane, urea, jojoba oil, crambe oil, Japanese soapnut tree (mukuroji) extract, allantoin, α-bisabolol, dipotassium glycyrrhizinate', ARRAY['gently cleanses and removes waterproof make-up from the eyes and lips', 'removes irritation, has a calming effect', 'softens the skin and prevents desquamation', 'intensively moisturizes the skin'], 'Apply to dry skin. Massage gently with circular motions all over the face, including the eye contour area. Rinse thoroughly with warm water or remove the remains using a warm wet towel.', 45.00, 'Cleansers'),

('ENZYME:CITRUS MASK', 'Innovative formula for delicate exfoliation, nutrition and skin colour improvement', '150 mL', 'enzyme complex with a high content of keratinase, licorice root extract, niacinamide, betaine, urea, microspheres with encapsulated vitamins, cellulobeads, trehalose', ARRAY['delicately removes keratinized epidermal cells and smooths the microrelief', 'improves blood circulation and skin tone', 'enriches the skin with vitamins and increases the bioavailability of subsequent care products', 'lightens pigment spots'], 'Scrub: apply a small amount of the product to the skin evenly, perform a light massage until the microspheres dissolve completely. Remove the remains with warm water.', 52.00, 'Masks'),

('HYDRO:COLD MASK', 'Prepares the skin for further professional procedures', '150 mL', 'aloe leaf juice, urea, betaine, glycerin', ARRAY['provides deep pore cleansing, removes keratinized cells', 'softens comedones', 'has a moisturizing and soothing effect', 'has healing, anti-inflammatory properties'], 'To prepare the skin for cosmetic procedures apply the mask for 5-7 minutes. Rinse thoroughly with water.', 38.00, 'Masks'),

('FRESH:LIGHT CREAM', 'Formula for flawless skin even without make-up', '50 mL', 'complex of great burnet, ginger root and cinnamon tree with a sebostatic effect, complex of prebiotics with α-glucan oligosaccharide, extract of honeysuckle flowers, licorice root extract, complex of ceramides, phytosphingosine and cholesterol, menthol derivative', ARRAY['mattifies, narrows pores and gives a feeling of freshness', 'prevents inflammation', 'moisturizes, restores the hydrolipid film', 'protects the skin from aggressive environmental influences'], 'Apply on dry skin of the whole face or T-zone after cleansing, avoiding the eye contour area. Massage gently with circular motions until the cream is completely absorbed.', 42.00, 'Moisturizers'),

('SILK:GLOSS CREAM', 'Formula with a delicate silky texture for daytime care or use as a make-up base', '50 mL', 'betaine, dipotassium glycyrrhizinate, complex of A, C, E and F vitamins, jojoba oil, complex of sphingolipids and phospholipids, aloe leaf juice', ARRAY['nourishes the skin, maintains its optimal level of moisture', 'gives the skin elasticity and silkiness', 'reduces inflammatory reactions, has a calming effect', 'protects against overdrying and exposure to unfavourable environmental factors'], 'Apply on dry skin after cleansing, massage gently with circular motions until the cream is completely absorbed.', 48.00, 'Moisturizers'),

('ANTI-ACNE CREAM', 'Cream for problem acne-prone skin', '50 mL', 'niacinamide, peptide for acne relief, zink PCA, peptide complex containing growth factors, azelaic acid, vitamin E, squalane, anti-inflammatory peptide, vitamin F, seboregulating complex', ARRAY['restores the damaged lipid barrier', 'controls oily shine', 'prevents and reduces inflammation', 'relieves redness', 'provides anti-inflammatory and antibacterial effect'], 'Apply on dry skin after cleansing, avoiding the eye contour area and lips. Massage gently with circular motions until the cream is completely absorbed.', 55.00, 'Treatments'),

('FLASH ANTI:AGE CREAM', 'Luxurious formula for competent daytime care of aging skin', '50 mL', 'matrikine, niacinamide, polysaccharide complex, licorice root extract, Sichuan pepper extract, complex of NMF components, betaine, vitamin E, α-glucan oligosaccharide, complex of sphingolipids and phospholipids, peptide with a botulinum-like effect', ARRAY['activates key renewal mechanisms of the skin', 'smooths the microrelief, improves the complexion and turgor', 'intensively moisturizes the skin, increases its moisture retention functions', 'protects against aggressive environmental influences', 'prevents the aging process of the skin, reduces the severity of wrinkles'], 'Apply on dry skin after cleansing, massage gently with circular motions until the cream is completely absorbed.', 68.00, 'Treatments'),

('PEPTIDE EYE CREAM', 'Cream for the eye contour area', '50 mL', 'lymphatic drainage peptide complex, phytoestrogens from wild yam root and soybeans, poria cocos extract, baobab seed oil, Sichuan pepper extract, complex of ceramides, phytosphingosine and cholesterol', ARRAY['nourishes and restores the skin around the eyes', 'reduces dark circles and puffiness in the eye contour area', 'improves skin elasticity and microcirculation', 'has a rejuvenating effect'], 'Apply on clean skin of the eye contour area or the whole face, massage gently with circular motions until the cream is completely absorbed.', 58.00, 'Treatments'),

('TRIPLE:ESSENCE', 'Anti-aging essence for skin structure renewal', '30 mL', 'peptide with a botulinum-like effect, matrikines, polysaccharide complex with α-glucan oligosaccharide, dipotassium glycyrrhizinate, Klotho rejuvenating factor peptide fragment, proteasome-activating peptide', ARRAY['reduces facial stress, smooths fine wrinkles', 'improves skin turgor and evens out the texture', 'activates local skin immunity', 'has an anti-inflammatory effect'], 'Apply on dry skin after cleansing, massage gently with sliding and tapping motions until the serum is completely absorbed. Apply a moisturizing cream to enhance the effect.', 75.00, 'Serums'),

('FRESH:FOAM', 'Light foam for the removal of water-soluble contaminants', '200 mL', 'soft surfactants based on coconut oil and betaine, lactic acid, complex of сentella, juniper, hazelnut, witch hazel, sage and thyme extracts, α-glucan oligosaccharide, dipotassium glycyrrhizinate, allantoin', ARRAY['gently removes excess sebum and water-soluble contaminants', 'prevents the occurrence of inflammatory processes', 'accelerates the process of natural cell renewal', 'regulates the activity of the sebaceous glands, promotes the narrowing of pores', 'activates the process of natural exfoliation of keratinized scales, whitening and smoothing the complexion'], 'Apply to wet skin. Massage gently with circular motions all over the face, including the eye contour area. Rinse thoroughly with water or remove the remains using a wet towel.', 35.00, 'Cleansers');
