-- Add all 36 products from Lebanon PDF with detailed descriptions
-- Clear existing products first to avoid duplicates
DELETE FROM products;

-- Reset the sequence to start from 1
ALTER SEQUENCE products_id_seq RESTART WITH 1;

INSERT INTO products (name, description, volume, price, category, active_ingredients, effects, directions, image_url, in_stock) VALUES

-- 1. CLEAR:UP EMULSION
('CLEAR:UP EMULSION', 'Light cleansing emulsion with a velvety texture for the removal of oil-soluble contaminants and make-up', '250 mL', 89.99, 'Cleansers', 'squalane, urea, jojoba oil, crambe oil, Japanese soapnut tree (mukuroji) extract, allantoin, α-bisabolol, dipotassium glycyrrhizinate', ARRAY['gently cleanses and removes waterproof make-up from the eyes and lips', 'removes irritation, has a calming effect', 'softens the skin and prevents desquamation', 'intensively moisturizes the skin'], 'Apply to dry skin. Massage gently with circular motions all over the face, including the eye contour area. Rinse thoroughly with warm water or remove the remains using a warm wet towel.', '/placeholder.svg?height=400&width=400', true),

-- 2. ENZYME:CITRUS MASK
('ENZYME:CITRUS MASK', 'Innovative formula for delicate exfoliation, nutrition and skin colour improvement', '150 mL', 125.99, 'Masks', 'enzyme complex with a high content of keratinase, licorice root extract, niacinamide, betaine, urea, microspheres with encapsulated vitamins, cellulobeads, trehalose', ARRAY['delicately removes keratinized epidermal cells and smooths the microrelief', 'improves blood circulation and skin tone', 'enriches the skin with vitamins and increases the bioavailability of subsequent care products', 'lightens pigment spots'], 'Scrub: apply a small amount of the product to the skin evenly, perform a light massage until the microspheres dissolve completely. Remove the remains with warm water. Mask: apply the product to the skin in a thin even layer, leave for 3-5 minutes. Remove the remains with warm water. Gommage: apply the product to the skin in a thin even layer, leave it to dry. Rub the product in with massage movements. Remove the remains with warm water.', '/placeholder.svg?height=400&width=400', true),

-- 3. HYDRO:COLD MASK
('HYDRO:COLD MASK', 'Prepares the skin for further professional procedures', '150 mL', 95.99, 'Masks', 'aloe leaf juice, urea, betaine, glycerin', ARRAY['provides deep pore cleansing, removes keratinized cells', 'softens comedones', 'has a moisturizing and soothing effect', 'has healing, anti-inflammatory properties'], '1. To prepare the skin for cosmetic procedures apply the mask for 5-7 minutes. Rinse thoroughly with water. 2. For deep mechanical cleansing apply the mask for 20-30 minutes using occlusion film. Remove the gel with warm water or using a warm wet towel.', '/placeholder.svg?height=400&width=400', true),

-- 4. FRESH:LIGHT CREAM
('FRESH:LIGHT CREAM', 'Formula for flawless skin even without make-up', '50 mL', 115.99, 'Moisturizers', 'complex of great burnet, ginger root and cinnamon tree with a sebostatic effect, complex of prebiotics with α-glucan oligosaccharide, extract of honeysuckle flowers, licorice root extract, complex of ceramides, phytosphingosine and cholesterol, menthol derivative', ARRAY['mattifies, narrows pores and gives a feeling of freshness', 'prevents inflammation', 'moisturizes, restores the hydrolipid film', 'protects the skin from aggressive environmental influences'], 'Apply on dry skin of the whole face or T-zone after cleansing, avoiding the eye contour area. Massage gently with circular motions until the cream is completely absorbed.', '/placeholder.svg?height=400&width=400', true),

-- 5. SILK:GLOSS CREAM
('SILK:GLOSS CREAM', 'Formula with a delicate silky texture for daytime care or use as a make-up base', '50 mL', 135.99, 'Moisturizers', 'betaine, dipotassium glycyrrhizinate, complex of A, C, E and F vitamins, jojoba oil, complex of sphingolipids and phospholipids, aloe leaf juice', ARRAY['nourishes the skin, maintains its optimal level of moisture', 'gives the skin elasticity and silkiness', 'reduces inflammatory reactions, has a calming effect', 'protects against overdrying and exposure to unfavourable environmental factors'], 'Apply on dry skin after cleansing, massage gently with circular motions until the cream is completely absorbed.', '/placeholder.svg?height=400&width=400', true),

-- 6. ANTI-ACNE CREAM
('ANTI-ACNE CREAM', 'Cream for problem acne-prone skin', '50 mL', 145.99, 'Acne Care', 'niacinamide, peptide for acne relief, zink PCA, peptide complex containing growth factors, azelaic acid, vitamin E, squalane, anti-inflammatory peptide, vitamin F, seboregulating complex', ARRAY['restores the damaged lipid barrier', 'controls oily shine', 'prevents and reduces inflammation', 'relieves redness', 'provides anti-inflammatory and antibacterial effect'], 'Apply on dry skin after cleansing, avoiding the eye contour area and lips. Massage gently with circular motions until the cream is completely absorbed.', '/placeholder.svg?height=400&width=400', true),

-- 7. FLASH ANTI:AGE CREAM
('FLASH ANTI:AGE CREAM', 'Luxurious formula for competent daytime care of aging skin', '50 mL', 165.99, 'Anti-Aging', 'matrikine, niacinamide, polysaccharide complex, licorice root extract, Sichuan pepper extract, complex of NMF components, betaine, vitamin E, α-glucan oligosaccharide, complex of sphingolipids and phospholipids, peptide with a botulinum-like effect', ARRAY['activates key renewal mechanisms of the skin', 'smooths the microrelief, improves the complexion and turgor', 'intensively moisturizes the skin, increases its moisture retention functions', 'protects against aggressive environmental influences', 'prevents the aging process of the skin, reduces the severity of wrinkles'], 'Apply on dry skin after cleansing, massage gently with circular motions until the cream is completely absorbed.', '/placeholder.svg?height=400&width=400', true),

-- 8. PEPTIDE EYE CREAM
('PEPTIDE EYE CREAM', 'Cream for the eye contour area', '50 mL', 155.99, 'Eye Care', 'lymphatic drainage peptide complex, phytoestrogens from wild yam root and soybeans, poria cocos extract, baobab seed oil, Sichuan pepper extract, complex of ceramides, phytosphingosine and cholesterol', ARRAY['nourishes and restores the skin around the eyes', 'reduces dark circles and puffiness in the eye contour area', 'improves skin elasticity and microcirculation', 'has a rejuvenating effect'], 'Apply on clean skin of the eye contour area or the whole face, massage gently with circular motions until the cream is completely absorbed.', '/placeholder.svg?height=400&width=400', true),

-- 9. TRIPLE:ESSENCE
('TRIPLE:ESSENCE', 'Anti-aging essence for skin structure renewal', '30 mL', 185.99, 'Serums', 'peptide with a botulinum-like effect, matrikines, polysaccharide complex with α-glucan oligosaccharide, dipotassium glycyrrhizinate, Klotho rejuvenating factor peptide fragment, proteasome-activating peptide', ARRAY['reduces facial stress, smooths fine wrinkles', 'improves skin turgor and evens out the texture', 'activates local skin immunity', 'has an anti-inflammatory effect'], 'Apply on dry skin after cleansing, massage gently with sliding and tapping motions until the serum is completely absorbed. Apply a moisturizing cream to enhance the effect.', '/placeholder.svg?height=400&width=400', true),

-- 10. FRESH:FOAM
('FRESH:FOAM', 'Light foam for the removal of water-soluble contaminants', '200 mL', 75.99, 'Cleansers', 'soft surfactants based on coconut oil and betaine, lactic acid, complex of сentella, juniper, hazelnut, witch hazel, sage and thyme extracts, α-glucan oligosaccharide, dipotassium glycyrrhizinate, allantoin', ARRAY['gently removes excess sebum and water-soluble contaminants', 'prevents the occurrence of inflammatory processes', 'accelerates the process of natural cell renewal', 'regulates the activity of the sebaceous glands, promotes the narrowing of pores', 'activates the process of natural exfoliation of keratinized scales, whitening and smoothing the complexion'], 'Apply to wet skin. Massage gently with circular motions all over the face, including the eye contour area. Rinse thoroughly with water or remove the remains using a wet towel.', '/placeholder.svg?height=400&width=400', true),

-- 11. FRESH POST:PEEL CREAM
('FRESH POST:PEEL CREAM', 'Lamellar emulsion for skin regeneration after aggressive exposure', '50 mL', 125.99, 'Treatments', 'urea, squalane, mimosa bark extract, complex of NMF components, pumpkin seed extract, sea water, polysaccharide complex with α-glucan oligosaccharide, complex of ceramides, phytosphingosine and cholesterol, fermented grape seed oil, hyaluronic acid', ARRAY['resumes the process of natural skin hydration', 'has astringent, antiseptic and toning effects', 'increases elasticity, promotes regeneration, has pronounced anti-inflammatory and soothing properties'], 'Apply on dry skin after cleansing, massage gently with circular motions. Recommended for use after the chemical peel procedure 2-3 times a day for 3 days or as a day cream for skin with pronounced flaking.', '/placeholder.svg?height=400&width=400', true),

-- 12. FRESH POST:PEEL LOTION
('FRESH POST:PEEL LOTION', 'Lotion for the acceleration of skin regeneration during post-peel care', '250 mL', 95.99, 'Toners', 'betaine, complex of NMF components, chitosan derivative', ARRAY['has a soothing and moisturizing effect on the skin after a chemical peel or other aggressive exposure', 'supports and restores NMF', 'has softening, antistatic and anti-inflammatory properties'], 'Apply to the skin as the final stage of cleansing using cotton pads. For peel neutralization, distribute the lotion over the skin surface using cotton pads or a brush, leave for 5 minutes and rinse thoroughly with water. Then apply again and do not rinse.', '/placeholder.svg?height=400&width=400', true),

-- 13. AQUA:BALANCE LOTION
('AQUA:BALANCE LOTION', 'The final step of skin cleansing for normalizing the skin pH level', '220 mL', 85.99, 'Toners', 'extract of honeysuckle flowers, aloe leaf juice, сurculigo root extract, dipotassium glycyrrhizinate, purple coneflower extract, anti-inflammatory complex of seven extracts (licorice, green tea, Baikal skullcap, Japanese knotweed, chamomile, centella, rosemary)', ARRAY['moisturizes the skin, restores the hydrolipid film and pH', 'improves microcirculation, strengthens the vessel walls and improves the complexion', 'improves skin immunity and tone', 'reduces inflammatory reactions, has a calming effect'], 'Shake before use. Apply to the skin after cleansing and each contact with water using abundantly soaked cotton pads.', '/placeholder.svg?height=400&width=400', true),

-- 14. HYDRO:ACTIVE CREAM
('HYDRO:ACTIVE CREAM', 'Universal all-season light-texture cream', '50 mL', 105.99, 'Moisturizers', 'trehalose, stearyl glycyrrhetinate, marsh samphire extract, α-bisabolol, active complex with β-glucan', ARRAY['eliminates the feeling of dryness and maintains the optimal level of hydration', 'softens and blocks the effects of drying factors (wind, sun)', 'promotes tissue regeneration, has a calming effect', 'prevents premature aging and skin pigmentation'], 'Apply on dry skin after cleansing, massage gently with circular motions until the cream is completely absorbed.', '/placeholder.svg?height=400&width=400', true),

-- 15. HYDRO:COMPLEX MASK
('HYDRO:COMPLEX MASK', 'Intensively moisturizing formula with a rich creamy texture', '150 mL', 115.99, 'Masks', 'aloe leaf juice, squalane, shea butter, natural complex of B vitamins, complex of NMF components, betaine, dipotassium glycyrrhizinate', ARRAY['nourishes the skin with essential fatty acids, vitamins and trace elements', 'restores the hydrolipid film and reduces the loss of moisture', 'promotes skin regeneration', 'increases skin turgor', 'smooths fine lines'], 'Apply a thick layer of the mask to dry clean skin, including the eye contour area and lips. On the areas where the mask is immediately absorbed, add a small quantity of the mask. Leave for 15-20 minutes. Remove the mask with a warm wet compress or rinse thoroughly with water.', '/placeholder.svg?height=400&width=400', true),

-- 16. NUTRI:ACTIVE INTENSE CREAM
('NUTRI:ACTIVE INTENSE CREAM', 'Cream for intensive personal skin care', '50 mL', 145.99, 'Moisturizers', 'natural oils of apricot kernel, shea and rosemary, complex of centella, chestnut, ivy and buckwheat, nano-liposomes with multivitamin complex A+C+E+F', ARRAY['promotes effective regeneration', 'nourishes, maintains the optimal level of moisture', 'improves the functions of the skin barrier, restores the hydrolipid film', 'has smoothing properties, prevents the appearance of wrinkles'], 'Apply on dry skin after cleansing, massage gently with circular motions until the cream is completely absorbed.', '/placeholder.svg?height=400&width=400', true),

-- 17. HAND SOFT:TOUCH CREAM
('HAND SOFT:TOUCH CREAM', 'Irreplaceable protective cream for daily care of hands, cuticles and nails', '150 mL', 65.99, 'Hand Care', 'shea butter, crambe oil, betaine, urea, complex of ceramides, phytosphingosine and cholesterol, α-bisabolol', ARRAY['softens, prevents desquamation and drying of the skin after contact with water', 'improves microcirculation', 'increases the production of collagen, improving skin firmness and elasticity', 'slows down the aging process, accelerates cell renewal'], 'Apply to dry clean skin of hands and massage until the cream is completely absorbed. Сan be used as often as necessary during the day.', '/placeholder.svg?height=400&width=400', true),

-- 18. FRESH:LIFT CREAM
('FRESH:LIFT CREAM', 'Remodeling cream of targeted action for personal skin care', '50 mL', 175.99, 'Anti-Aging', 'high molecular weight biopolymer from sweet almond proteins, polysaccharide complex, Sichuan pepper extract, DMAE, moringa seed extract, shea butter, hyaluronic acid, vitamin E', ARRAY['improves skin tone, smooths wrinkles', 'provides prolonged lifting', 'has a powerful antioxidant effect', 'prevents dryness', 'slows down the process of photoaging'], 'Apply on dry skin after cleansing, massage gently with circular motions until the cream is completely absorbed.', '/placeholder.svg?height=400&width=400', true),

-- 19. CONTOUR:FACE MASK
('CONTOUR:FACE MASK', 'Cream mask for targeted personal skin care', '50 mL', 155.99, 'Masks', 'high molecular weight biopolymer from sweet almond proteins, complex of plant extracts (horse chestnut, butcher''s broom, centella, grape leaf, ivy, buckwheat), dipotassium glycyrrhizinate, polysaccharide complex with β-glucan, acmella extract, ginkgo biloba extract, troxerutin', ARRAY['strengthens the skin', 'provides prolonged lifting', 'has an anti-edematous effect, removes toxins', 'increases skin elasticity, strengthens the vessel walls', 'reduces wrinkles'], 'Apply a thick layer of the mask on dry clean face and neck, including the eye contour area and lips. On the areas where the mask is immediately absorbed, add a small quantity of the mask to obtain an even bright layer. Leave for 15-20 minutes. Remove the mask with a warm wet compress or rinse thoroughly with water.', '/placeholder.svg?height=400&width=400', true),

-- 20. ORANGE:LIFT MASK
('ORANGE:LIFT MASK', 'Effective peel-off mask for skin rejuvenation and exfoliation', '50 mL', 135.99, 'Masks', 'complex of NMF components, hyaluronic acid, flax seed extract, microencapsulated retinol', ARRAY['restores healthy complexion', 'smooths the network of fine lines and intensively moisturizes the skin', 'provides firm lifting', 'improves cell metabolism and increases local immunity'], 'Apply on dry clean face, avoiding the eye contour area and lips. Leave for 20-30 minutes. Carefully peel off the mask upwards from the chin to forehead.', '/placeholder.svg?height=400&width=400', true),

-- 21. FLASH:LIFT ESSENCE
('FLASH:LIFT ESSENCE', 'Enriched essence with a gel-like texture for strengthening of the dermal matrix', '30 mL', 195.99, 'Serums', 'high molecular weight biopolymer from sweet almond proteins, trehalose, polysaccharide complex with β-glucan, low molecular weight hyaluronic acid, peptide with a botulinum-like effect, matrikines, vitamin B3-based peptide', ARRAY['provides firm lifting, revitalizes the skin and gives it radiance', 'reduces facial stress, smoothing fine wrinkles and lines', 'improves skin tone, evens out the microrelief', 'restores the hydrolipid film'], 'Apply on dry skin after cleansing, massage gently with sliding and tapping motions until the serum is completely absorbed. Apply a moisturizing cream to enhance the effect.', '/placeholder.svg?height=400&width=400', true),

-- 22. BLEMISH:CONTROL MASK
('BLEMISH:CONTROL MASK', 'Highly effective formula for redness- and swelling-prone skin', '150 mL', 125.99, 'Masks', 'dipotassium glycyrrhizinate, ginkgo biloba extract, troxerutin, complex of plant extracts (horse chestnut, butcher''s broom, centella, grape leaf, ivy, buckwheat)', ARRAY['strengthens and tones blood vessels, making them less visible', 'has drainage properties, removes toxins', 'blocks free radicals, reduces redness'], 'Apply a thick layer of the mask to dry clean skin, including the eye contour area and lips. On the areas where the mask is immediately absorbed, add a small quantity of the mask. Leave for 15-20 minutes. Remove the mask with a warm wet compress or rinse thoroughly with water.', '/placeholder.svg?height=400&width=400', true),

-- 23. BRILLIANCE:SERUM
('BRILLIANCE:SERUM', 'Highly active fluid for targeted personal skin care', '30 mL', 165.99, 'Serums', 'complex of arginine salt PCA and Brazilian ginseng root extract with a high content of polyphenols, whitening peptide for the correction of pigment spots, α-glucan oligosaccharide, vitamin C, ginkgo biloba and olive leaf extracts', ARRAY['lightens pigment spots', 'suppresses the effect of free radicals and activates cell renewal', 'slows down the process of photoaging', 'smooths wrinkles, evens out the complexion', 'strengthens the vessel walls, reduces the manifestations of couperosis'], 'Apply on dry skin after cleansing, massage gently with sliding and tapping motions until the serum is completely absorbed. Apply a moisturizing cream to enhance the effect.', '/placeholder.svg?height=400&width=400', true),

-- 24. AHA GEL
('AHA GEL', 'Exfoliating cleanser with fruit acids', '400 mL', 115.99, 'Cleansers', 'exfoliating complex based on apple extract and AHA-acids (glycolic, lactic), complex of plant extracts (horse chestnut, butcher''s broom, centella, grape leaf, ivy, buckwheat), complex of NMF components', ARRAY['Cleansing and exfoliating product with fruit acids', 'particularly recommended as a part of regular care of oily, problem and acne-prone skin', 'promotes intensive pore cleansing, removes inflammation and relieves desquamation', 'recommended for pre-peel care'], 'Apply the gel to wet face and neck, massage gently with circular motions. Rinse thoroughly with water. For deep cleansing and extra exfoliation use 1-2 times a week.', '/placeholder.svg?height=400&width=400', true),

-- 25. MULTI ACTIVE CREAM
('MULTI ACTIVE CREAM', 'Moisturizing cream', '200 mL', 95.99, 'Moisturizers', 'lactobacillus lysate, vitamin E, fermented grape seed oil, D-panthenol, multifunctional complex containing four hydrolyzed proteins derived from wheat, corn, oat, soybeans, complex of A and C vitamins, B vitamins, NMF components', ARRAY['provides intensive hydration, tones and firms the skin', 'slows down the aging processes, enhances cell regeneration', 'restores the natural barrier of the skin', 'has a strong antioxidant effect, protects the skin from free radicals', 'relieves irritation and itching', 'reduces the degree of damage to DNA and protein molecules from UV rays'], 'Apply on dry skin after cleansing, massage gently with circular motions until the cream is completely absorbed.', '/placeholder.svg?height=400&width=400', true),

-- 26. NEUTRO:SENSE CREAM
('NEUTRO:SENSE CREAM', 'Soothing cream for targeted personal skin care', '50 mL', 135.99, 'Sensitive Care', 'complex of ceramides, phytosphingosine and cholesterol, α-glucan oligosaccharide, peptide inhibitor of neurogenic inflammation, dipotassium glycyrrhizinate, Sichuan pepper extract, ectoin, glycerin, moringa seed extract, squalane', ARRAY['increases the immune status of the skin, restores the damaged hydrolipid film', 'soothes the skin, reduces irritation and itching', 'prevents the appearance of couperosis', 'removes inflammation caused by various factors (UV, exposure to cold, etc.)'], 'Apply on dry skin after cleansing, massage gently with circular motions until the cream is completely absorbed.', '/placeholder.svg?height=400&width=400', true),

-- 27. Revital:Active Mask
('Revital:Active Mask', 'Sterile mask with soothing and regenerative effect for finishing invasive cosmetic procedures', '33 mL', 45.99, 'Masks', 'aloe leaf juice, niacinamide, hyaluronic acid, dipotassium glycyrrhizinate, arnica extract, allantoin', ARRAY['special nonwoven Japanese fabric impregnated with serum', 'serum formulation immediately and effectively relieves neurogenic skin irritation', 'has an anti-inflammatory effect, reduces erythema and edema', 'promotes healing, soothes the skin'], 'Apply the mask to the skin of the face and neck after the procedure, carefully spread it for maximum contact with the skin, remove the mask after 15-20 minutes. For single use. Do not rinse.', '/placeholder.svg?height=400&width=400', true),

-- 28. AGE RESIST
('AGE RESIST', 'Innovative rejuvenating mask', '25 g x 5 pcs', 225.99, 'Masks', 'matrikines, red quinoa seed extract, wild yam root extract, trehalose, betaine', ARRAY['biocellulose layer that adheres to the surface like a second skin', 'increases ability of the epidermis to retain moisture', 'serum enriched with peptides and precious plant extracts', 'increases skin elasticity, restores the integrity of the skin barrier', 'provides deep hydration', 'instantly improves the appearance of the skin'], 'Take the mask out of the package, unfold it and remove the top protective film. Apply the mask to the face after cleansing, then remove the second protective film. Carefully spread the mask for maximum contact with the skin. Remove the mask after 20-25 minutes and massage the skin gently until excess serum is completely absorbed. Do not rinse.', '/placeholder.svg?height=400&width=400', true),

-- 29. Hydro Line
('Hydro Line', 'Professional mesotherapy solution for intensive revitalization', '4 mL', 85.99, 'Professional Treatments', 'hyaluronic acid 0,5% (800 kDa), amino acids, B vitamins, antioxidants, buffer system', ARRAY['intensive revitalization', 'deep hydration', 'anti-stress and anti-age treatment', 'increasing skin immunity', 'improving hair quality'], 'Professional use only. For mesotherapy procedures by qualified practitioners.', '/placeholder.svg?height=400&width=400', true),

-- 30. MesoHydral Silicio
('MesoHydral Silicio', 'Professional mesotherapy solution with silicon complex', '5 mL', 95.99, 'Professional Treatments', 'hyaluronic acid 1.5% (800 kDa), silicon and glucosamine complex, buffer system', ARRAY['hydration', 'strengthening dermal matrix', 'improving skin colour'], 'Professional use only. For mesotherapy procedures by qualified practitioners.', '/placeholder.svg?height=400&width=400', true),

-- 31. Hair X Vita Line B+
('Hair X Vita Line B+', 'Professional hair treatment solution', '4 mL', 75.99, 'Professional Treatments', 'B vitamins, amino acids, buffer system', ARRAY['anti-stress and anti-age treatment', 'anti-acne treatment', 'hair growth enhancement', 'improving hair quality', 'increasing skin immunity'], 'Professional use only. For mesotherapy procedures by qualified practitioners.', '/placeholder.svg?height=400&width=400', true),

-- 32. Hair X B Complex
('Hair X B Complex', 'Professional B vitamin complex for comprehensive trichology', '5 mL', 85.99, 'Professional Treatments', 'B vitamins, buffer system', ARRAY['comprehensive trichology programs', 'increasing skin immunity', 'anti-acne treatment', 'anti-inflammatory treatment'], 'Professional use only. For mesotherapy procedures by qualified practitioners.', '/placeholder.svg?height=400&width=400', true),

-- 33. Ginkgo
('Ginkgo', 'Professional capillary mesotherapy solution', '4 mL', 65.99, 'Professional Treatments', 'herbal extract of ginkgo biloba, buffer system', ARRAY['capillary mesotherapy', 'microcirculation improvement', 'improvement of vessel wall tone', 'reducing the severity of dark circles under the eyes', 'reducing edema'], 'Professional use only. For mesotherapy procedures by qualified practitioners.', '/placeholder.svg?height=400&width=400', true),

-- 34. DVL Capyl
('DVL Capyl', 'Professional vascular treatment solution', '5 mL', 105.99, 'Professional Treatments', 'troxerutin, ginkgo biloba extract, buffer system', ARRAY['сapillary mesotherapy', 'restoration of the elasticity of blood vessels', 'cellulite treatment', 'treatment of couperosis', 'drainage/lymphatic drainage'], 'Professional use only. For mesotherapy procedures by qualified practitioners.', '/placeholder.svg?height=400&width=400', true),

-- 35. PHDC Forte
('PHDC Forte', 'Professional lipolysis solution', '5 mL', 145.99, 'Professional Treatments', 'L-carnitine, caffeine, organic silicon, rutin, melilot, sodium deoxycholate, phosphatidylcholine, buffer system', ARRAY['lipolysis', 'local fat deposits treatment', 'destruction of adipocyte membranes'], 'Professional use only. For mesotherapy procedures by qualified practitioners. Not more than 10 mL of PHDC Forte per session. Do not store in the refrigerator!', '/placeholder.svg?height=400&width=400', true),

-- 36. Phyto Slim
('Phyto Slim', 'Professional body contouring solution', '5 mL', 95.99, 'Professional Treatments', 'L-carnitine, caffeine, rutin, melilot, organic silicon, buffer system', ARRAY['local fat deposits treatment', 'cellulite treatment'], 'Professional use only. For mesotherapy procedures by qualified practitioners.', '/placeholder.svg?height=400&width=400', true);
