-- Add second batch of 10 Mesopharm products with actual images and converted prices
-- Exchange rate: 1 USD = 3.7563 SAR (as of December 2024)

INSERT INTO products (
  id,
  name,
  description,
  price,
  original_price,
  image_url,
  category,
  brand,
  in_stock,
  stock_quantity,
  rating,
  reviews_count,
  ingredients,
  how_to_use,
  skin_type,
  concerns,
  size,
  created_at,
  updated_at
) VALUES 
-- 1. AHA Gel - 280 SAR = $74.55 USD
(
  gen_random_uuid(),
  'Simple Care AHA Gel',
  'Exfoliating cleanser with fruit acids for normal and oily skin. Perfect for acne-prone skin and as a pre-peel preparation treatment.',
  74.55,
  NULL,
  '/images/products/mesopharm-aha-gel.png',
  'cleansers',
  'Mesopharm',
  true,
  25,
  4.6,
  18,
  'Alpha Hydroxy Acids (AHA), Fruit Acids, Glycolic Acid, Lactic Acid, Purified Water',
  'Apply to damp skin, massage gently for 1-2 minutes, rinse thoroughly with water. Use 2-3 times per week initially.',
  'oily,combination',
  'acne,blackheads,uneven_texture',
  '150ml',
  NOW(),
  NOW()
),

-- 2. Flash Anti Age Cream - 320 SAR = $85.19 USD
(
  gen_random_uuid(),
  'Flash Anti Age Cream',
  'Professional anti-aging cream that provides intensive nutrition and regeneration for mature skin. Reduces fine lines and improves skin elasticity.',
  85.19,
  NULL,
  '/images/products/mesopharm-flash-anti-age.jpg',
  'moisturizers',
  'Mesopharm',
  true,
  20,
  4.7,
  24,
  'Retinol, Peptides, Hyaluronic Acid, Vitamin E, Collagen Boosters, Antioxidant Complex',
  'Apply to clean face and neck in the evening. Use sunscreen during the day when using this product.',
  'mature,dry',
  'aging,fine_lines,loss_of_firmness',
  '50ml',
  NOW(),
  NOW()
),

-- 3. Mesohydral Ampoules - 450 SAR = $119.81 USD
(
  gen_random_uuid(),
  'Mesohydral HA Ampoules',
  'Professional hyaluronic acid ampoules for intensive hydration and skin plumping. Contains 800kDa molecular weight HA for maximum effectiveness.',
  119.81,
  NULL,
  '/images/products/mesopharm-mesohydral.jpg',
  'serums',
  'Mesopharm',
  true,
  15,
  4.8,
  31,
  'Hyaluronic Acid 800kDa, Sodium Hyaluronate, Purified Water, Preservative System',
  'Break ampoule carefully. Apply entire contents to clean face and neck. Use one ampoule every 2-3 days.',
  'all_skin_types',
  'dehydration,fine_lines,dullness',
  '5x5ml',
  NOW(),
  NOW()
),

-- 4. Hydro-Active Cream - 290 SAR = $77.21 USD
(
  gen_random_uuid(),
  'Hydro-Active Moisturizing Cream',
  'Intensive moisturizing cream for dehydrated skin. Restores natural hydration levels and strengthens the skin barrier.',
  77.21,
  NULL,
  '/images/products/mesopharm-hydro-active.png',
  'moisturizers',
  'Mesopharm',
  true,
  30,
  4.5,
  22,
  'Hyaluronic Acid, Ceramides, Glycerin, Squalane, Vitamin B5, Aqua Complex',
  'Apply morning and evening to clean face and neck. Massage gently until fully absorbed.',
  'dry,dehydrated',
  'dehydration,tightness,flaking',
  '50ml',
  NOW(),
  NOW()
),

-- 5. Neutro Sense Cream - 310 SAR = $82.53 USD
(
  gen_random_uuid(),
  'Neutro Sense Sensitive Skin Cream',
  'Gentle cream specially formulated for sensitive skin. Provides redness relief, nutrition, and protection against environmental stressors.',
  82.53,
  NULL,
  '/images/products/mesopharm-neutro-sense.png',
  'moisturizers',
  'Mesopharm',
  true,
  22,
  4.6,
  19,
  'Centella Asiatica, Niacinamide, Ceramides, Allantoin, Bisabolol, Thermal Water',
  'Apply morning and evening to clean face. Gentle enough for daily use on sensitive areas.',
  'sensitive,reactive',
  'redness,irritation,sensitivity',
  '50ml',
  NOW(),
  NOW()
),

-- 6. Brilliance Serum - 380 SAR = $101.15 USD
(
  gen_random_uuid(),
  'Brilliance Anti-Age Serum',
  'Advanced anti-aging serum for complexion improvement. Brightens skin tone, reduces dark spots, and enhances overall radiance.',
  101.15,
  NULL,
  '/images/products/mesopharm-brilliance-serum.jpg',
  'serums',
  'Mesopharm',
  true,
  18,
  4.7,
  26,
  'Vitamin C, Kojic Acid, Arbutin, Niacinamide, Alpha Arbutin, Licorice Extract',
  'Apply 2-3 drops to clean face in the evening. Always use sunscreen during the day.',
  'all_skin_types',
  'dark_spots,dullness,uneven_tone',
  '30ml',
  NOW(),
  NOW()
),

-- 7. Hydro Complex Mask - 250 SAR = $66.55 USD
(
  gen_random_uuid(),
  'Hydro Complex Moisturizing Mask',
  'Deep moisturizing mask for dehydrated skin. Provides intensive hydration and helps restore skin suppleness and comfort.',
  66.55,
  NULL,
  '/images/products/mesopharm-hydro-complex-mask.jpg',
  'masks',
  'Mesopharm',
  true,
  28,
  4.4,
  15,
  'Hyaluronic Acid, Glycerin, Aloe Vera, Panthenol, Marine Collagen, Cucumber Extract',
  'Apply thick layer to clean face, leave for 15-20 minutes, rinse with lukewarm water. Use 2-3 times per week.',
  'dry,dehydrated',
  'dehydration,tightness,dullness',
  '150ml',
  NOW(),
  NOW()
),

-- 8. Anti-Acne Cream - 270 SAR = $71.89 USD
(
  gen_random_uuid(),
  'Anti-Acne Treatment Cream',
  'Professional anti-acne cream for problem skin. Reduces pore size, controls oil production, and prevents breakouts.',
  71.89,
  NULL,
  '/images/products/mesopharm-anti-acne.png',
  'treatments',
  'Mesopharm',
  true,
  24,
  4.5,
  21,
  'Salicylic Acid, Niacinamide, Zinc Oxide, Tea Tree Oil, Sulfur, Bentonite Clay',
  'Apply thin layer to affected areas after cleansing. Start with once daily, increase as tolerated.',
  'oily,acne_prone',
  'acne,large_pores,excess_oil',
  '50ml',
  NOW(),
  NOW()
),

-- 9. Nutri Active Intense Cream - 340 SAR = $90.52 USD
(
  gen_random_uuid(),
  'Nutri Active Intense Nourishing Cream',
  'Rich nourishing cream for dry skin. Provides deep nutrition, recovery, and long-lasting moisture for compromised skin barriers.',
  90.52,
  NULL,
  '/images/products/mesopharm-nutri-active.png',
  'moisturizers',
  'Mesopharm',
  true,
  19,
  4.6,
  17,
  'Shea Butter, Ceramides, Peptides, Vitamin E, Jojoba Oil, Squalane, Cholesterol',
  'Apply morning and evening to clean face and neck. Massage until fully absorbed. Perfect for night use.',
  'dry,very_dry',
  'dryness,flaking,rough_texture',
  '50ml',
  NOW(),
  NOW()
),

-- 10. Fresh Post Peel Cream - 300 SAR = $79.87 USD
(
  gen_random_uuid(),
  'Fresh Post Peel Recovery Cream',
  'Specialized recovery cream for post-peel care. Restores skin barrier, soothes irritation, and accelerates healing process.',
  79.87,
  NULL,
  '/images/products/mesopharm-fresh-post-peel.png',
  'treatments',
  'Mesopharm',
  true,
  16,
  4.7,
  13,
  'Panthenol, Allantoin, Ceramides, Hyaluronic Acid, Centella Asiatica, Bisabolol',
  'Apply generously to treated areas 2-3 times daily after chemical peels. Use until skin is fully healed.',
  'post_treatment',
  'post_peel_care,irritation,healing',
  '50ml',
  NOW(),
  NOW()
);

-- Verify the insertions
SELECT name, price, brand, category FROM products WHERE brand = 'Mesopharm' ORDER BY created_at DESC LIMIT 10;
