-- Add 10 new ABS Beauty Pharm products with detailed information
-- These are professional skincare products with comprehensive descriptions

INSERT INTO products (name, description, volume, price, category, active_ingredients, effects, directions, image_url, in_stock) VALUES

-- 1. CLEAR:UP EMULSION
('CLEAR:UP EMULSION', 'Light cleansing emulsion with a velvety texture for the removal of oil-soluble contaminants and make-up. This professional-grade cleanser gently removes waterproof makeup while maintaining skin balance and providing intensive moisture.', '250 mL', 89.99, 'Cleansers', 'squalane, urea, jojoba oil, crambe oil, Japanese soapnut tree (mukuroji) extract, allantoin, α-bisabolol, dipotassium glycyrrhizinate', ARRAY['gently cleanses and removes waterproof make-up from the eyes and lips', 'removes irritation, has a calming effect', 'softens the skin and prevents desquamation', 'intensively moisturizes the skin'], 'Apply to dry skin. Massage gently with circular motions all over the face, including the eye contour area. Rinse thoroughly with warm water or remove the remains using a warm wet towel.', '/placeholder.svg?height=400&width=400', true),

-- 2. ENZYME:CITRUS MASK
('ENZYME:CITRUS MASK', 'Innovative formula for delicate exfoliation, nutrition and skin colour improvement. This multi-functional product can be used as a scrub, mask, or gommage treatment for versatile skincare benefits.', '150 mL', 125.99, 'Masks', 'enzyme complex with a high content of keratinase, licorice root extract, niacinamide, betaine, urea, microspheres with encapsulated vitamins, cellulobeads, trehalose', ARRAY['delicately removes keratinized epidermal cells and smooths the microrelief', 'improves blood circulation and skin tone', 'enriches the skin with vitamins and increases the bioavailability of subsequent care products', 'lightens pigment spots'], 'Scrub: apply a small amount of the product to the skin evenly, perform a light massage until the microspheres dissolve completely. Remove the remains with warm water. Mask: apply the product to the skin in a thin even layer, leave for 3-5 minutes. Remove the remains with warm water. Gommage: apply the product to the skin in a thin even layer, leave it to dry. Rub the product in with massage movements. Remove the remains with warm water.', '/placeholder.svg?height=400&width=400', true),

-- 3. HYDRO:COLD MASK
('HYDRO:COLD MASK', 'Prepares the skin for further professional procedures. This cooling mask provides deep pore cleansing and softens comedones while delivering moisturizing and soothing benefits with healing, anti-inflammatory properties.', '150 mL', 95.99, 'Masks', 'aloe leaf juice, urea, betaine, glycerin', ARRAY['provides deep pore cleansing, removes keratinized cells', 'softens comedones', 'has a moisturizing and soothing effect', 'has healing, anti-inflammatory properties'], '1. To prepare the skin for cosmetic procedures apply the mask for 5-7 minutes. Rinse thoroughly with water. 2. For deep mechanical cleansing apply the mask for 20-30 minutes using occlusion film. Remove the gel with warm water or using a warm wet towel.', '/placeholder.svg?height=400&width=400', true),

-- 4. FRESH:LIGHT CREAM
('FRESH:LIGHT CREAM', 'Formula for flawless skin even without make-up. This lightweight cream mattifies the skin, narrows pores, and provides a refreshing sensation while preventing inflammation and protecting against environmental damage.', '50 mL', 75.99, 'Moisturizers', 'complex of great burnet, ginger root and cinnamon tree with a sebostatic effect, complex of prebiotics with α-glucan oligosaccharide, extract of honeysuckle flowers, licorice root extract, complex of ceramides, phytosphingosine and cholesterol, menthol derivative', ARRAY['mattifies, narrows pores and gives a feeling of freshness', 'prevents inflammation', 'moisturizes, restores the hydrolipid film', 'protects the skin from aggressive environmental influences'], 'Apply on dry skin of the whole face or T-zone after cleansing, avoiding the eye contour area. Massage gently with circular motions until the cream is completely absorbed.', '/placeholder.svg?height=400&width=400', true),

-- 5. SILK:GLOSS CREAM
('SILK:GLOSS CREAM', 'Formula with a delicate silky texture for daytime care or use as a make-up base. This luxurious cream nourishes the skin while providing elasticity and silkiness, making it perfect for daily use or as a primer.', '50 mL', 85.99, 'Moisturizers', 'betaine, dipotassium glycyrrhizinate, complex of A, C, E and F vitamins, jojoba oil, complex of sphingolipids and phospholipids, aloe leaf juice', ARRAY['nourishes the skin, maintains its optimal level of moisture', 'gives the skin elasticity and silkiness', 'reduces inflammatory reactions, has a calming effect', 'protects against overdrying and exposure to unfavourable environmental factors'], 'Apply on dry skin after cleansing, massage gently with circular motions until the cream is completely absorbed.', '/placeholder.svg?height=400&width=400', true),

-- 6. ANTI-ACNE CREAM
('ANTI-ACNE CREAM', 'Cream for problem acne-prone skin. This specialized treatment cream restores the damaged lipid barrier while controlling oily shine and providing anti-inflammatory and antibacterial effects for clearer, healthier skin.', '50 mL', 95.99, 'Treatments', 'niacinamide, peptide for acne relief, zink PCA, peptide complex containing growth factors, azelaic acid, vitamin E, squalane, anti-inflammatory peptide, vitamin F, seboregulating complex', ARRAY['restores the damaged lipid barrier', 'controls oily shine', 'prevents and reduces inflammation', 'relieves redness', 'provides anti-inflammatory and antibacterial effect'], 'Apply on dry skin after cleansing, avoiding the eye contour area and lips. Massage gently with circular motions until the cream is completely absorbed.', '/placeholder.svg?height=400&width=400', true),

-- 7. FLASH ANTI:AGE CREAM
('FLASH ANTI:AGE CREAM', 'Luxurious formula for competent daytime care of aging skin. This advanced anti-aging cream activates key renewal mechanisms while smoothing microrelief and providing intensive moisture retention for youthful-looking skin.', '50 mL', 145.99, 'Anti-Aging', 'matrikine, niacinamide, polysaccharide complex, licorice root extract, Sichuan pepper extract, complex of NMF components, betaine, vitamin E, α-glucan oligosaccharide, complex of sphingolipids and phospholipids, peptide with a botulinum-like effect', ARRAY['activates key renewal mechanisms of the skin', 'smooths the microrelief, improves the complexion and turgor', 'intensively moisturizes the skin, increases its moisture retention functions', 'protects against aggressive environmental influences', 'prevents the aging process of the skin, reduces the severity of wrinkles'], 'Apply on dry skin after cleansing, massage gently with circular motions until the cream is completely absorbed.', '/placeholder.svg?height=400&width=400', true),

-- 8. PEPTIDE EYE CREAM
('PEPTIDE EYE CREAM', 'Cream for the eye contour area. This specialized eye treatment nourishes and restores the delicate skin around the eyes while reducing dark circles and puffiness for a more youthful, refreshed appearance.', '50 mL', 115.99, 'Eye Care', 'lymphatic drainage peptide complex, phytoestrogens from wild yam root and soybeans, poria cocos extract, baobab seed oil, Sichuan pepper extract, complex of ceramides, phytosphingosine and cholesterol', ARRAY['nourishes and restores the skin around the eyes', 'reduces dark circles and puffiness in the eye contour area', 'improves skin elasticity and microcirculation', 'has a rejuvenating effect'], 'Apply on clean skin of the eye contour area or the whole face, massage gently with circular motions until the cream is completely absorbed.', '/placeholder.svg?height=400&width=400', true),

-- 9. TRIPLE:ESSENCE
('TRIPLE:ESSENCE', 'Anti-aging essence for skin structure renewal. This concentrated essence reduces facial stress and smooths fine wrinkles while improving skin turgor and activating local skin immunity for comprehensive anti-aging benefits.', '30 mL', 165.99, 'Serums', 'peptide with a botulinum-like effect, matrikines, polysaccharide complex with α-glucan oligosaccharide, dipotassium glycyrrhizinate, Klotho rejuvenating factor peptide fragment, proteasome-activating peptide', ARRAY['reduces facial stress, smooths fine wrinkles', 'improves skin turgor and evens out the texture', 'activates local skin immunity', 'has an anti-inflammatory effect'], 'Apply on dry skin after cleansing, massage gently with sliding and tapping motions until the serum is completely absorbed. Apply a moisturizing cream to enhance the effect.', '/placeholder.svg?height=400&width=400', true),

-- 10. FRESH:FOAM
('FRESH:FOAM', 'Light foam for the removal of water-soluble contaminants. This gentle foaming cleanser removes excess sebum and water-soluble contaminants while preventing inflammatory processes and promoting natural cell renewal.', '200 mL', 65.99, 'Cleansers', 'soft surfactants based on coconut oil and betaine, lactic acid, complex of сentella, juniper, hazelnut, witch hazel, sage and thyme extracts, α-glucan oligosaccharide, dipotassium glycyrrhizinate, allantoin', ARRAY['gently removes excess sebum and water-soluble contaminants', 'prevents the occurrence of inflammatory processes', 'accelerates the process of natural cell renewal', 'regulates the activity of the sebaceous glands, promotes the narrowing of pores', 'activates the process of natural exfoliation of keratinized scales, whitening and smoothing the complexion'], 'Apply to wet skin. Massage gently with circular motions all over the face, including the eye contour area. Rinse thoroughly with water or remove the remains using a wet towel.', '/placeholder.svg?height=400&width=400', true);
