-- Add 10 additional ABS Beauty Pharm products (products 11-20)
-- All products priced at $79.99 with placeholder images for now

INSERT INTO products (name, description, volume, price, category, active_ingredients, effects, directions, image_url, in_stock) VALUES

-- Product 11: FRESH POST:PEEL CREAM
('FRESH POST:PEEL CREAM', 'Lamellar emulsion for skin regeneration after aggressive exposure. This specialized post-peel cream helps restore and soothe skin following chemical peels or other intensive treatments.', '50ml', 79.99, 'Post-Treatment', 'urea, squalane, mimosa bark extract, complex of NMF components, pumpkin seed extract, sea water, polysaccharide complex with α-glucan oligosaccharide, complex of ceramides, phytosphingosine and cholesterol, fermented grape seed oil, hyaluronic acid', ARRAY['Resumes natural skin hydration', 'Has astringent, antiseptic and toning effects', 'Increases elasticity and promotes regeneration', 'Has pronounced anti-inflammatory properties', 'Provides soothing effects'], 'Apply on dry skin after cleansing, massage gently with circular motions. Recommended for use after the chemical peel procedure 2-3 times a day for 3 days or as a day cream for skin with pronounced flaking.', '/placeholder.svg?height=400&width=400', true),

-- Product 12: FRESH POST:PEEL LOTION
('FRESH POST:PEEL LOTION', 'Lotion for the acceleration of skin regeneration during post-peel care. This gentle lotion soothes and moisturizes skin after chemical peels or aggressive treatments.', '250ml', 79.99, 'Post-Treatment', 'betaine, complex of NMF components, chitosan derivative', ARRAY['Has soothing and moisturizing effect after chemical peel', 'Supports and restores NMF', 'Has softening and antistatic properties', 'Provides anti-inflammatory benefits'], 'Apply to the skin as the final stage of cleansing using cotton pads. For peel neutralization, distribute the lotion over the skin surface using cotton pads or a brush, leave for 5 minutes and rinse thoroughly with water. Then apply again and do not rinse.', '/placeholder.svg?height=400&width=400', true),

-- Product 13: AQUA:BALANCE LOTION
('AQUA:BALANCE LOTION', 'The final step of skin cleansing for normalizing the skin pH level. This balancing lotion restores optimal skin pH while providing hydration and anti-inflammatory benefits.', '220ml', 79.99, 'Toners', 'extract of honeysuckle flowers, aloe leaf juice, сurculigo root extract, dipotassium glycyrrhizinate, purple coneflower extract, anti-inflammatory complex of seven extracts (licorice, green tea, Baikal skullcap, Japanese knotweed, chamomile, centella, rosemary)', ARRAY['Moisturizes skin and restores hydrolipid film and pH', 'Improves microcirculation and strengthens vessel walls', 'Improves complexion and skin immunity', 'Reduces inflammatory reactions', 'Has calming effect'], 'Shake before use. Apply to the skin after cleansing and each contact with water using abundantly soaked cotton pads.', '/placeholder.svg?height=400&width=400', true),

-- Product 14: HYDRO:ACTIVE CREAM
('HYDRO:ACTIVE CREAM', 'Universal all-season light-texture cream. This versatile moisturizer provides optimal hydration while protecting against environmental stressors year-round.', '50ml', 79.99, 'Moisturizers', 'trehalose, stearyl glycyrrhetinate, marsh samphire extract, α-bisabolol, active complex with β-glucan', ARRAY['Eliminates feeling of dryness', 'Maintains optimal level of hydration', 'Softens and blocks effects of drying factors', 'Promotes tissue regeneration', 'Has calming effect', 'Prevents premature aging and skin pigmentation'], 'Apply on dry skin after cleansing, massage gently with circular motions until the cream is completely absorbed.', '/placeholder.svg?height=400&width=400', true),

-- Product 15: HYDRO:COMPLEX MASK
('HYDRO:COMPLEX MASK', 'Intensively moisturizing formula with a rich creamy texture. This nourishing mask provides deep hydration and essential nutrients for skin regeneration.', '150ml', 79.99, 'Masks', 'aloe leaf juice, squalane, shea butter, natural complex of B vitamins, complex of NMF components, betaine, dipotassium glycyrrhizinate', ARRAY['Nourishes skin with essential fatty acids, vitamins and trace elements', 'Restores hydrolipid film and reduces moisture loss', 'Promotes skin regeneration', 'Increases skin turgor', 'Smooths fine lines'], 'Apply a thick layer of the mask to dry clean skin, including the eye contour area and lips. On the areas where the mask is immediately absorbed, add a small quantity of the mask. Leave for 15-20 minutes. Remove the mask with a warm wet compress or rinse thoroughly with water.', '/placeholder.svg?height=400&width=400', true),

-- Product 16: NUTRI:ACTIVE INTENSE CREAM
('NUTRI:ACTIVE INTENSE CREAM', 'Cream for intensive personal skin care. This rich nourishing cream provides deep nutrition and promotes effective skin regeneration with natural oils and vitamins.', '50ml', 79.99, 'Moisturizers', 'natural oils of apricot kernel, shea and rosemary, complex of centella, chestnut, ivy and buckwheat, nano-liposomes with multivitamin complex A+C+E+F', ARRAY['Promotes effective regeneration', 'Nourishes and maintains optimal moisture level', 'Improves skin barrier functions', 'Restores hydrolipid film', 'Has smoothing properties', 'Prevents appearance of wrinkles'], 'Apply on dry skin after cleansing, massage gently with circular motions until the cream is completely absorbed.', '/placeholder.svg?height=400&width=400', true),

-- Product 17: HAND SOFT:TOUCH CREAM
('HAND SOFT:TOUCH CREAM', 'Irreplaceable protective cream for daily care of hands, cuticles and nails. This specialized hand cream provides comprehensive care for hands, cuticles, and nails.', '150ml', 79.99, 'Hand Care', 'shea butter, crambe oil, betaine, urea, complex of ceramides, phytosphingosine and cholesterol, α-bisabolol', ARRAY['Softens and prevents desquamation', 'Prevents drying after contact with water', 'Improves microcirculation', 'Increases collagen production', 'Improves skin firmness and elasticity', 'Slows down aging process', 'Accelerates cell renewal'], 'Apply to dry clean skin of hands and massage until the cream is completely absorbed. Can be used as often as necessary during the day.', '/placeholder.svg?height=400&width=400', true),

-- Product 18: FRESH:LIFT CREAM
('FRESH:LIFT CREAM', 'Remodeling cream of targeted action for personal skin care. This advanced lifting cream provides firming effects and anti-aging benefits with powerful active ingredients.', '50ml', 79.99, 'Anti-Aging', 'high molecular weight biopolymer from sweet almond proteins, polysaccharide complex, Sichuan pepper extract, DMAE, moringa seed extract, shea butter, hyaluronic acid, vitamin E', ARRAY['Improves skin tone and smooths wrinkles', 'Provides prolonged lifting effect', 'Has powerful antioxidant effect', 'Prevents dryness', 'Slows down process of photoaging'], 'Apply on dry skin after cleansing, massage gently with circular motions until the cream is completely absorbed.', '/placeholder.svg?height=400&width=400', true),

-- Product 19: CONTOUR:FACE MASK
('CONTOUR:FACE MASK', 'Cream mask for targeted personal skin care. This specialized contouring mask strengthens skin and provides lifting effects while reducing signs of aging.', '50ml', 79.99, 'Masks', 'high molecular weight biopolymer from sweet almond proteins, complex of plant extracts (horse chestnut, butcher''s broom, centella, grape leaf, ivy, buckwheat), dipotassium glycyrrhizinate, polysaccharide complex with β-glucan, acmella extract, ginkgo biloba extract, troxerutin', ARRAY['Strengthens the skin', 'Provides prolonged lifting effect', 'Has anti-edematous effect', 'Removes toxins', 'Increases skin elasticity', 'Strengthens vessel walls', 'Reduces wrinkles'], 'Apply a thick layer of the mask on dry clean face and neck, including the eye contour area and lips. On the areas where the mask is immediately absorbed, add a small quantity of the mask to obtain an even bright layer. Leave for 15-20 minutes. Remove the mask with a warm wet compress or rinse thoroughly with water.', '/placeholder.svg?height=400&width=400', true),

-- Product 20: ORANGE:LIFT MASK
('ORANGE:LIFT MASK', 'Effective peel-off mask for skin rejuvenation and exfoliation. This innovative peel-off mask provides lifting effects while improving skin texture and appearance.', '50ml', 79.99, 'Masks', 'complex of NMF components, hyaluronic acid, flax seed extract, microencapsulated retinol', ARRAY['Restores healthy complexion', 'Smooths network of fine lines', 'Intensively moisturizes skin', 'Provides firm lifting effect', 'Improves cell metabolism', 'Increases local immunity'], 'Apply on dry clean face, avoiding the eye contour area and lips. Leave for 20-30 minutes. Carefully peel off the mask upwards from the chin to forehead.', '/placeholder.svg?height=400&width=400', true);
