-- Add 10 more ABS Beauty Pharm products (batch 3) with detailed information
-- All products priced at $79.99 as requested

INSERT INTO products (name, description, volume, price, category, active_ingredients, effects, directions, image_url, in_stock) VALUES

-- 21. FLASH:LIFT ESSENCE
('FLASH:LIFT ESSENCE', 'Enriched essence with a gel-like texture for strengthening of the dermal matrix. This advanced lifting essence provides firm lifting while revitalizing the skin and giving it radiance, reducing facial stress and smoothing fine wrinkles.', '30 mL', 79.99, 'Serums', 'high molecular weight biopolymer from sweet almond proteins, trehalose, polysaccharide complex with β-glucan, low molecular weight hyaluronic acid, peptide with a botulinum-like effect, matrikines, vitamin B3-based peptide', ARRAY['provides firm lifting, revitalizes the skin and gives it radiance', 'reduces facial stress, smoothing fine wrinkles and lines', 'improves skin tone, evens out the microrelief', 'restores the hydrolipid film'], 'Apply on dry skin after cleansing, massage gently with sliding and tapping motions until the serum is completely absorbed. Apply a moisturizing cream to enhance the effect.', '/placeholder.svg?height=400&width=400', true),

-- 22. BLEMISH:CONTROL MASK
('BLEMISH:CONTROL MASK', 'Highly effective formula for redness- and swelling-prone skin. This specialized mask strengthens and tones blood vessels while providing drainage properties and blocking free radicals to reduce redness and inflammation.', '150 mL', 79.99, 'Masks', 'dipotassium glycyrrhizinate, ginkgo biloba extract, troxerutin, complex of plant extracts (horse chestnut, butcher''s broom, centella, grape leaf, ivy, buckwheat)', ARRAY['strengthens and tones blood vessels, making them less visible', 'has drainage properties, removes toxins', 'blocks free radicals, reduces redness'], 'Apply a thick layer of the mask to dry clean skin, including the eye contour area and lips. On the areas where the mask is immediately absorbed, add a small quantity of the mask. Leave for 15-20 minutes. Remove the mask with a warm wet compress or rinse thoroughly with water.', '/placeholder.svg?height=400&width=400', true),

-- 23. BRILLIANCE:SERUM
('BRILLIANCE:SERUM', 'Highly active fluid for targeted personal skin care. This brightening serum lightens pigment spots while suppressing free radicals and activating cell renewal to slow down photoaging and strengthen vessel walls.', '30 mL', 79.99, 'Serums', 'complex of arginine salt PCA and Brazilian ginseng root extract with a high content of polyphenols, whitening peptide for the correction of pigment spots, α-glucan oligosaccharide, vitamin C, ginkgo biloba and olive leaf extracts', ARRAY['lightens pigment spots', 'suppresses the effect of free radicals and activates cell renewal', 'slows down the process of photoaging', 'smooths wrinkles, evens out the complexion', 'strengthens the vessel walls, reduces the manifestations of couperosis'], 'Apply on dry skin after cleansing, massage gently with sliding and tapping motions until the serum is completely absorbed. Apply a moisturizing cream to enhance the effect.', '/placeholder.svg?height=400&width=400', true),

-- 24. AHA GEL
('AHA GEL', 'Exfoliating cleanser with fruit acids. This cleansing and exfoliating product with fruit acids is particularly recommended as part of regular care for oily, problem and acne-prone skin, promoting intensive pore cleansing.', '150 mL', 79.99, 'Cleansers', 'exfoliating complex based on apple extract and AHA-acids (glycolic, lactic), complex of plant extracts (horse chestnut, butcher''s broom, centella, grape leaf, ivy, buckwheat), complex of NMF components', ARRAY['promotes intensive pore cleansing', 'removes inflammation and relieves desquamation', 'particularly recommended for oily, problem and acne-prone skin', 'recommended for pre-peel care'], 'Apply the gel to wet face and neck, massage gently with circular motions. Rinse thoroughly with water. For deep cleansing and extra exfoliation use 1-2 times a week.', '/placeholder.svg?height=400&width=400', true),

-- 25. MULTI ACTIVE CREAM
('MULTI ACTIVE CREAM', 'Moisturizing cream that provides intensive hydration, tones and firms the skin while slowing down aging processes. This comprehensive cream enhances cell regeneration and restores the natural skin barrier with strong antioxidant effects.', '200 mL', 79.99, 'Moisturizers', 'lactobacillus lysate, vitamin E, fermented grape seed oil, D-panthenol, multifunctional complex containing four hydrolyzed proteins derived from wheat, corn, oat, soybeans, complex of A and C vitamins, B vitamins, NMF components', ARRAY['provides intensive hydration, tones and firms the skin', 'slows down the aging processes, enhances cell regeneration', 'restores the natural barrier of the skin', 'has a strong antioxidant effect, protects from free radicals', 'relieves irritation and itching', 'reduces DNA and protein damage from UV rays'], 'Apply on dry skin after cleansing, massage gently with circular motions until the cream is completely absorbed.', '/placeholder.svg?height=400&width=400', true),

-- 26. NEUTRO:SENSE CREAM
('NEUTRO:SENSE CREAM', 'Soothing cream for targeted personal skin care. This specialized cream increases skin immune status while soothing irritation and preventing couperosis, making it ideal for sensitive and reactive skin types.', '50 mL', 79.99, 'Treatments', 'complex of ceramides, phytosphingosine and cholesterol, α-glucan oligosaccharide, peptide inhibitor of neurogenic inflammation, dipotassium glycyrrhizinate, Sichuan pepper extract, ectoin, glycerin, moringa seed extract, squalane', ARRAY['increases the immune status of the skin, restores the damaged hydrolipid film', 'soothes the skin, reduces irritation and itching', 'prevents the appearance of couperosis', 'removes inflammation caused by various factors (UV, exposure to cold, etc.)'], 'Apply on dry skin after cleansing, massage gently with circular motions until the cream is completely absorbed.', '/placeholder.svg?height=400&width=400', true),

-- 27. REVITAL:ACTIVE MASK
('REVITAL:ACTIVE MASK', 'Sterile mask with soothing and regenerative effect for finishing invasive cosmetic procedures. This special nonwoven Japanese fabric mask is impregnated with serum that immediately relieves neurogenic skin irritation.', '33 mL', 79.99, 'Masks', 'aloe leaf juice, niacinamide, hyaluronic acid, dipotassium glycyrrhizinate, arnica extract, allantoin', ARRAY['special nonwoven Japanese fabric impregnated with serum', 'serum formulation immediately and effectively relieves neurogenic skin irritation', 'has an anti-inflammatory effect, reduces erythema and edema', 'promotes healing, soothes the skin'], 'Apply the mask to the skin of the face and neck after the procedure, carefully spread it for maximum contact with the skin, remove the mask after 15-20 minutes. For single use. Do not rinse.', '/placeholder.svg?height=400&width=400', true),

-- 28. AGE RESIST
('AGE RESIST', 'Innovative rejuvenating mask with dual-system technology. Features a biocellulose layer that adheres like a second skin and serum enriched with peptides and precious plant extracts for deep hydration and improved skin elasticity.', '25 g x 5 pcs', 79.99, 'Masks', 'matrikines, red quinoa seed extract, wild yam root extract, trehalose, betaine', ARRAY['biocellulose layer adheres to the surface like a second skin', 'increases ability of epidermis to retain moisture', 'active components penetrate deeply without impairing skin breathing', 'increases skin elasticity, restores integrity of skin barrier', 'provides deep hydration', 'instantly improves appearance of the skin'], 'Take the mask out of the package, unfold it and remove the top protective film. Apply the mask to the face after cleansing, then remove the second protective film. Carefully spread the mask for maximum contact with the skin. Remove the mask after 20-25 minutes and massage the skin gently until excess serum is completely absorbed. Do not rinse.', '/placeholder.svg?height=400&width=400', true),

-- 29. HYDRO LINE
('HYDRO LINE', 'Professional mesotherapy solution for intensive revitalization and deep hydration. This advanced formula provides anti-stress and anti-age treatment while increasing skin immunity and improving overall skin quality.', '4 mL', 79.99, 'Treatments', 'hyaluronic acid 0.5% (800 kDa), amino acids, B vitamins, antioxidants, buffer system', ARRAY['intensive revitalization', 'deep hydration', 'anti-stress and anti-age treatment', 'increasing skin immunity', 'improving hair quality'], 'Professional use only. For mesotherapy and professional treatments. Follow professional protocols for application.', '/placeholder.svg?height=400&width=400', true),

-- 30. MESOHYDRAL SILICIO
('MESOHYDRAL SILICIO', 'Professional mesotherapy solution with silicon and glucosamine complex. This specialized treatment provides hydration while strengthening the dermal matrix and improving skin color for professional aesthetic procedures.', '5 mL', 79.99, 'Treatments', 'hyaluronic acid 1.5% (800 kDa), silicon and glucosamine complex, buffer system', ARRAY['hydration', 'strengthening dermal matrix', 'improving skin colour'], 'Professional use only. For mesotherapy and professional treatments. Follow professional protocols for application.', '/placeholder.svg?height=400&width=400', true);
