-- Add 9 new ABS Beauty Pharm products (batch 4) - Hair care, mesotherapy, and specialized treatments
-- All products priced at $79.99 as requested

INSERT INTO products (name, description, volume, price, category, active_ingredients, effects, directions, image_url, in_stock) VALUES

-- 31. Hair X Vita Line B+
('Hair X Vita Line B+', 'Professional mesotherapy solution enriched with B vitamins and amino acids for comprehensive hair and skin treatment. This advanced formula provides anti-stress and anti-aging benefits while enhancing hair growth and improving overall hair quality.', '4 mL', 79.99, 'Mesotherapy', 'B vitamins, amino acids, buffer system', ARRAY['anti-stress and anti-age treatment', 'anti-acne treatment', 'hair growth enhancement', 'improving hair quality', 'increasing skin immunity'], 'For professional mesotherapy use only. Administer according to professional protocols for hair and skin treatments.', '/placeholder.svg?height=400&width=400', true),

-- 32. Hair X B Complex
('Hair X B Complex', 'Specialized B vitamin complex for comprehensive trichology programs and skin immunity enhancement. This professional-grade solution provides anti-inflammatory benefits and supports comprehensive hair care treatments.', '5 mL', 79.99, 'Mesotherapy', 'B vitamins, buffer system', ARRAY['comprehensive trichology programs', 'increasing skin immunity', 'anti-acne treatment', 'anti-inflammatory treatment'], 'For professional mesotherapy use only. Use as part of comprehensive trichology and dermatological treatment programs.', '/placeholder.svg?height=400&width=400', true),

-- 33. Ginkgo
('Ginkgo', 'Herbal extract mesotherapy solution featuring ginkgo biloba for capillary treatments and microcirculation improvement. This natural formula enhances vessel wall tone while reducing dark circles and edema for improved skin appearance.', '4 mL', 79.99, 'Mesotherapy', 'herbal extract of ginkgo biloba, buffer system', ARRAY['capillary mesotherapy', 'microcirculation improvement', 'improvement of vessel wall tone', 'reducing the severity of dark circles under the eyes', 'reducing edema'], 'For professional mesotherapy use only. Ideal for capillary treatments and microcirculation enhancement protocols.', '/placeholder.svg?height=400&width=400', true),

-- 34. DVL Capyl
('DVL Capyl', 'Advanced capillary mesotherapy solution combining troxerutin and ginkgo biloba extract for vessel restoration and cellulite treatment. This professional formula provides drainage benefits and treats couperosis effectively.', '5 mL', 79.99, 'Mesotherapy', 'troxerutin, ginkgo biloba extract, buffer system', ARRAY['сapillary mesotherapy', 'restoration of the elasticity of blood vessels', 'cellulite treatment', 'treatment of couperosis', 'drainage/lymphatic drainage'], 'For professional mesotherapy use only. Excellent for capillary treatments, cellulite reduction, and lymphatic drainage protocols.', '/placeholder.svg?height=400&width=400', true),

-- 35. PHDC Forte
('PHDC Forte', 'Powerful lipolysis solution for local fat deposit treatment and adipocyte membrane destruction. This concentrated formula combines L-carnitine, caffeine, and phosphatidylcholine for effective body contouring treatments. Maximum 10 mL per session. Do not refrigerate.', '5 mL', 79.99, 'Mesotherapy', 'L-carnitine, caffeine, organic silicon, rutin, melilot, sodium deoxycholate, phosphatidylcholine, buffer system', ARRAY['lipolysis', 'local fat deposits treatment', 'destruction of adipocyte membranes'], 'For professional mesotherapy use only. Maximum 10 mL per session. Do not store in refrigerator. Use for targeted fat reduction and body contouring treatments.', '/placeholder.svg?height=400&width=400', true),

-- 36. Phyto Slim
('Phyto Slim', 'Natural slimming solution combining L-carnitine, caffeine, and botanical extracts for local fat deposit and cellulite treatment. This plant-based formula provides effective body contouring benefits through natural active ingredients.', '5 mL', 79.99, 'Mesotherapy', 'L-carnitine, caffeine, rutin, melilot, organic silicon, buffer system', ARRAY['local fat deposits treatment', 'cellulite treatment'], 'For professional mesotherapy use only. Ideal for natural body contouring and cellulite reduction treatments.', '/placeholder.svg?height=400&width=400', true),

-- 37. Nucleospire Revitalizing Complex A Shine
('Nucleospire Revitalizing Complex A Shine', 'Revitalizing complex featuring hyaluronic acid, vitamins B and C, and antioxidants for hyperpigmentation treatment and skin brightening. This advanced formula improves skin color and provides anti-stress benefits, particularly effective for smokers skin.', '4 mL', 79.99, 'Mesotherapy', 'hyaluronic acid 0.5% (800 kDa), vitamins B and C, antioxidants, buffer system', ARRAY['hyperpigmentation', 'anti-stress and anti-age treatment', 'improving colour of smokers skin'], 'For professional mesotherapy use only. Excellent for treating hyperpigmentation and improving overall skin radiance and color.', '/placeholder.svg?height=400&width=400', true),

-- 38. Vita Line C
('Vita Line C', 'High-concentration vitamin C solution (20%) for hyperpigmentation treatment and skin immunity enhancement. This potent antioxidant formula treats couperosis and provides anti-inflammatory benefits. Do not mix with other products.', '5 mL', 79.99, 'Mesotherapy', 'vitamin C 20%, buffer system', ARRAY['hyperpigmentation', 'increasing skin immunity', 'treatment of couperosis', 'anti-stress treatment', 'anti-inflammatory treatment'], 'For professional mesotherapy use only. Do not mix with other products. Ideal for treating hyperpigmentation and boosting skin immunity.', '/placeholder.svg?height=400&width=400', true),

-- 39. SENSITIVE TONER
('SENSITIVE TONER', 'Specialized toner designed for dry and sensitive skin with betaine and glyceryl glucoside. This gentle cleansing toner effectively restores microcirculation, strengthens vessel walls, and carefully moisturizes while restoring natural pH balance without irritation.', '400 mL', 79.99, 'Toners', 'betaine, glyceryl glucoside', ARRAY['effectively restores microcirculation', 'strengthens the vessel walls', 'carefully moisturizes and tones the skin without irritation', 'restoring natural pH level'], 'Apply to the skin after cleansing and each contact with water using abundantly soaked cotton pads.', '/placeholder.svg?height=400&width=400', true);
