-- Insert initial products for Neon database
INSERT INTO products (name, description, price, volume, active_ingredients, category, effects, image_url, in_stock) VALUES
('Hydrating Face Serum', 'A deeply moisturizing serum with hyaluronic acid for all skin types', 79.99, '30ml', ARRAY['Hyaluronic Acid', 'Vitamin E', 'Glycerin'], 'Serums', ARRAY['Hydrating', 'Anti-aging'], '/placeholder.svg?height=400&width=400', true),
('Vitamin C Brightening Cream', 'Brightening cream with vitamin C to even skin tone and reduce dark spots', 79.99, '50ml', ARRAY['Vitamin C', 'Niacinamide', 'Alpha Arbutin'], 'Moisturizers', ARRAY['Brightening', 'Anti-aging'], '/placeholder.svg?height=400&width=400', true),
('Retinol Night Treatment', 'Powerful anti-aging night treatment with retinol for smoother skin', 79.99, '30ml', ARRAY['Retinol', 'Peptides', 'Squalane'], 'Treatments', ARRAY['Anti-aging', 'Smoothing'], '/placeholder.svg?height=400&width=400', true),
('Gentle Cleansing Foam', 'Mild foaming cleanser that removes impurities without stripping skin', 79.99, '150ml', ARRAY['Salicylic Acid', 'Chamomile Extract', 'Aloe Vera'], 'Cleansers', ARRAY['Cleansing', 'Soothing'], '/placeholder.svg?height=400&width=400', true),
('SPF 50 Daily Sunscreen', 'Broad-spectrum sunscreen with SPF 50 for daily protection', 79.99, '50ml', ARRAY['Zinc Oxide', 'Titanium Dioxide', 'Vitamin E'], 'Sunscreens', ARRAY['Protection', 'Moisturizing'], '/placeholder.svg?height=400&width=400', true),
('Exfoliating Toner', 'Gentle exfoliating toner with AHA/BHA for smoother, brighter skin', 79.99, '200ml', ARRAY['Glycolic Acid', 'Salicylic Acid', 'Witch Hazel'], 'Toners', ARRAY['Exfoliating', 'Brightening'], '/placeholder.svg?height=400&width=400', true),
('Eye Repair Cream', 'Intensive eye cream targeting fine lines and dark circles', 79.99, '15ml', ARRAY['Caffeine', 'Peptides', 'Hyaluronic Acid'], 'Eye Care', ARRAY['Anti-aging', 'Brightening'], '/placeholder.svg?height=400&width=400', true),
('Nourishing Face Oil', 'Luxurious face oil blend for deep nourishment and glow', 79.99, '30ml', ARRAY['Rosehip Oil', 'Jojoba Oil', 'Vitamin E'], 'Oils', ARRAY['Nourishing', 'Glowing'], '/placeholder.svg?height=400&width=400', true),
('Purifying Clay Mask', 'Deep-cleansing clay mask for oily and combination skin', 79.99, '75ml', ARRAY['Bentonite Clay', 'Charcoal', 'Tea Tree Oil'], 'Masks', ARRAY['Purifying', 'Cleansing'], '/placeholder.svg?height=400&width=400', true);
