-- Updated seed script for Supabase with all 36 Mesopharm products
INSERT INTO products (id, name, description, volume, price, category, effects, active_ingredients, directions, image_url, in_stock, created_at, updated_at) VALUES
(gen_random_uuid(), 'Clear.Up Emulsion', 'Professional cleansing emulsion that effectively removes impurities and makeup while maintaining optimal skin hydration. Specially formulated for all skin types including sensitive skin.', '200ml', 45.00, 'Cleansers', ARRAY['Deep cleansing', 'Makeup removal', 'Hydrating'], 'Glycerin, Chamomile Extract, Vitamin E', 'Apply to dry skin, massage gently, then rinse with lukewarm water. Use morning and evening.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-MThp38gGFU1Sh2YO0Bt5blh5kqsIVz.png', true, NOW(), NOW()),

(gen_random_uuid(), 'Luxury Cleansing Emulsion', 'A gentle yet effective cleansing emulsion that removes makeup and impurities while maintaining skin hydration. Perfect for all skin types including sensitive skin.', '200ml', 45.00, 'Cleansers', ARRAY['Deep cleansing', 'Makeup removal', 'Hydrating'], 'Glycerin, Chamomile Extract, Vitamin E', 'Apply to dry skin, massage gently, then rinse with lukewarm water. Use morning and evening.', '/luxury-cleansing-emulsion-bottle.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Citrus Enzyme Face Mask', 'Brightening enzyme mask with natural citrus extracts that gently exfoliates and reveals radiant, glowing skin. Contains vitamin C for antioxidant protection.', '75ml', 38.00, 'Masks', ARRAY['Brightening', 'Exfoliating', 'Antioxidant protection'], 'Citrus Extract, Papaya Enzyme, Vitamin C, Alpha Hydroxy Acids', 'Apply thin layer to clean skin, leave for 10-15 minutes, then rinse thoroughly. Use 2-3 times per week.', '/citrus-enzyme-face-mask-jar.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Hydrating Cold Face Mask', 'Cooling gel mask that provides instant hydration and soothes irritated skin. Perfect for post-treatment care or hot weather relief.', '100ml', 32.00, 'Masks', ARRAY['Instant hydration', 'Cooling effect', 'Soothing'], 'Hyaluronic Acid, Aloe Vera, Cucumber Extract, Menthol', 'Apply generous layer to clean skin, leave for 15-20 minutes, then remove excess. Can be used daily.', '/hydrating-cold-face-mask-gel.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Light Moisturizing Face Cream', 'Lightweight daily moisturizer that provides long-lasting hydration without clogging pores. Ideal for normal to oily skin types.', '50ml', 42.00, 'Moisturizers', ARRAY['Daily hydration', 'Non-comedogenic', 'Oil control'], 'Niacinamide, Hyaluronic Acid, Green Tea Extract', 'Apply to clean face and neck morning and evening. Massage gently until absorbed.', '/light-moisturizing-face-cream-tube.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Silky Day Cream', 'Luxurious day cream with SPF protection that leaves skin feeling silky smooth. Contains anti-aging ingredients for daily protection.', '50ml', 55.00, 'Moisturizers', ARRAY['SPF protection', 'Anti-aging', 'Silky texture'], 'SPF 30, Peptides, Vitamin E, Silk Proteins', 'Apply to face and neck every morning as the last step of skincare routine. Reapply as needed.', '/silky-day-cream-luxury-skincare-jar.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Anti-Acne Treatment Cream', 'Targeted treatment cream for acne-prone skin that reduces breakouts and prevents future blemishes while maintaining skin balance.', '30ml', 48.00, 'Treatments', ARRAY['Acne treatment', 'Breakout prevention', 'Oil control'], 'Salicylic Acid, Tea Tree Oil, Zinc Oxide, Niacinamide', 'Apply thin layer to affected areas after cleansing. Start with once daily, increase as tolerated.', '/anti-acne-treatment-cream-tube.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Luxury Anti-Aging Face Cream', 'Premium anti-aging cream with advanced peptides and retinol that reduces fine lines and improves skin elasticity for a youthful appearance.', '50ml', 85.00, 'Anti-Aging', ARRAY['Reduces fine lines', 'Improves elasticity', 'Firming'], 'Retinol, Peptides, Collagen, Vitamin C', 'Apply to clean face and neck in the evening. Use sunscreen during the day when using this product.', '/luxury-anti-aging-face-cream-jar.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Peptide Eye Cream', 'Specialized eye cream with peptides that targets dark circles, puffiness, and fine lines around the delicate eye area.', '15ml', 65.00, 'Eye Care', ARRAY['Reduces dark circles', 'Anti-puffiness', 'Fine line reduction'], 'Peptides, Caffeine, Vitamin K, Hyaluronic Acid', 'Gently pat small amount around eye area morning and evening. Avoid direct contact with eyes.', '/peptide-eye-cream-tube-luxury.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Vitamin C Brightening Serum', 'Potent vitamin C serum that brightens skin tone, reduces dark spots, and provides antioxidant protection against environmental damage.', '30ml', 58.00, 'Serums', ARRAY['Brightening', 'Dark spot reduction', 'Antioxidant protection'], 'Vitamin C 20%, Vitamin E, Ferulic Acid', 'Apply 2-3 drops to clean face before moisturizer. Use in morning with sunscreen.', '/vitamin-c-brightening-serum-bottle.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Hyaluronic Acid Hydrating Serum', 'Intensive hydrating serum with multiple types of hyaluronic acid that plumps skin and provides deep, long-lasting moisture.', '30ml', 52.00, 'Serums', ARRAY['Deep hydration', 'Plumping effect', 'Long-lasting moisture'], 'Hyaluronic Acid, Sodium Hyaluronate, Glycerin', 'Apply to damp skin before moisturizer. Can be used morning and evening.', '/hyaluronic-acid-hydrating-serum.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Retinol Night Treatment', 'Advanced retinol treatment that accelerates cell turnover, reduces signs of aging, and improves skin texture overnight.', '30ml', 72.00, 'Treatments', ARRAY['Cell renewal', 'Anti-aging', 'Texture improvement'], 'Retinol 0.5%, Squalane, Vitamin E', 'Apply thin layer to clean face 2-3 times per week initially. Always use sunscreen during the day.', '/retinol-night-treatment-bottle.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Gentle Exfoliating Scrub', 'Mild exfoliating scrub with natural microbeads that removes dead skin cells and reveals smoother, brighter skin without irritation.', '100ml', 35.00, 'Exfoliants', ARRAY['Gentle exfoliation', 'Brightening', 'Smoothing'], 'Jojoba Beads, Glycolic Acid, Chamomile Extract', 'Massage gently on damp skin in circular motions. Rinse thoroughly. Use 2-3 times per week.', '/gentle-exfoliating-scrub-tube.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Nourishing Night Cream', 'Rich night cream that repairs and regenerates skin while you sleep, leaving you with a refreshed, glowing complexion in the morning.', '50ml', 62.00, 'Moisturizers', ARRAY['Night repair', 'Regenerating', 'Nourishing'], 'Ceramides, Peptides, Shea Butter, Vitamin A', 'Apply generously to clean face and neck before bedtime. Massage until absorbed.', '/nourishing-night-cream-jar.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Sensitive Skin Calming Toner', 'Alcohol-free toner specially formulated for sensitive skin that balances pH, soothes irritation, and prepares skin for treatments.', '200ml', 28.00, 'Toners', ARRAY['pH balancing', 'Soothing', 'Calming'], 'Rose Water, Allantoin, Panthenol, Chamomile', 'Apply to clean face with cotton pad or pat gently with hands. Use morning and evening.', '/sensitive-skin-calming-toner.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Brightening Face Wash', 'Daily brightening cleanser with gentle acids that removes impurities while promoting a more even, radiant skin tone.', '150ml', 32.00, 'Cleansers', ARRAY['Daily cleansing', 'Brightening', 'Even skin tone'], 'Lactic Acid, Kojic Acid, Vitamin C, Licorice Extract', 'Massage onto wet face, work into lather, then rinse thoroughly. Use morning and evening.', '/brightening-face-wash-tube.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Collagen Boosting Mask', 'Weekly treatment mask that stimulates collagen production, firms skin, and reduces the appearance of fine lines and wrinkles.', '75ml', 68.00, 'Masks', ARRAY['Collagen stimulation', 'Firming', 'Anti-wrinkle'], 'Marine Collagen, Peptides, Vitamin C, Elastin', 'Apply thick layer to clean skin, leave for 20 minutes, then rinse. Use once weekly.', '/collagen-boosting-mask-jar.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Oil-Free Sunscreen SPF 50', 'Lightweight, oil-free sunscreen that provides broad-spectrum protection without leaving white residue or clogging pores.', '50ml', 38.00, 'Sun Protection', ARRAY['SPF 50 protection', 'Oil-free', 'Non-comedogenic'], 'Zinc Oxide, Titanium Dioxide, Niacinamide', 'Apply generously 15 minutes before sun exposure. Reapply every 2 hours or after swimming.', '/oil-free-sunscreen-spf50.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Purifying Clay Mask', 'Deep-cleansing clay mask that draws out impurities, excess oil, and toxins while minimizing the appearance of pores.', '100ml', 42.00, 'Masks', ARRAY['Deep cleansing', 'Pore minimizing', 'Oil control'], 'Bentonite Clay, Kaolin, Tea Tree Oil, Charcoal', 'Apply even layer to clean skin, avoid eye area. Leave for 10-15 minutes until dry, then rinse.', '/purifying-clay-mask-jar.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Intensive Repair Serum', 'Concentrated repair serum with growth factors and stem cells that accelerates healing and regeneration of damaged skin.', '30ml', 95.00, 'Serums', ARRAY['Skin repair', 'Regeneration', 'Healing'], 'Growth Factors, Plant Stem Cells, Copper Peptides', 'Apply 2-3 drops to clean skin before moisturizer. Use morning and evening for best results.', '/intensive-repair-serum-bottle.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Gentle Makeup Remover', 'Bi-phase makeup remover that effectively removes waterproof makeup and impurities without harsh rubbing or irritation.', '150ml', 25.00, 'Cleansers', ARRAY['Makeup removal', 'Gentle formula', 'Waterproof'], 'Micellar Water, Jojoba Oil, Vitamin E', 'Shake well before use. Apply to cotton pad and gently press on closed eyes, then wipe away makeup.', '/gentle-makeup-remover-bottle.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Antioxidant Face Mist', 'Refreshing antioxidant mist that can be used throughout the day to hydrate, protect, and revitalize skin on-the-go.', '100ml', 28.00, 'Mists', ARRAY['Hydrating', 'Antioxidant protection', 'Refreshing'], 'Green Tea Extract, Vitamin E, Rose Water, Aloe Vera', 'Spray evenly on face from 6 inches away. Can be used over makeup or on clean skin.', '/antioxidant-face-mist-spray.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Firming Neck Cream', 'Specialized neck and décolletage cream that firms, tightens, and improves the appearance of sagging skin in these delicate areas.', '50ml', 75.00, 'Specialized Care', ARRAY['Firming', 'Tightening', 'Neck care'], 'Peptides, DMAE, Elastin, Vitamin C', 'Apply to clean neck and décolletage with upward strokes. Use morning and evening.', '/firming-neck-cream-tube.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Acne Spot Treatment', 'Fast-acting spot treatment that targets individual blemishes, reduces inflammation, and speeds healing without over-drying.', '15ml', 22.00, 'Treatments', ARRAY['Spot treatment', 'Fast-acting', 'Anti-inflammatory'], 'Benzoyl Peroxide, Salicylic Acid, Tea Tree Oil', 'Apply small amount directly to blemish. Use 1-2 times daily. May cause dryness initially.', '/acne-spot-treatment-tube.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Hydrating Lip Treatment', 'Intensive lip treatment that repairs, protects, and maintains soft, smooth lips with long-lasting hydration.', '15ml', 18.00, 'Lip Care', ARRAY['Lip repair', 'Long-lasting hydration', 'Protection'], 'Shea Butter, Vitamin E, Beeswax, Peptides', 'Apply to lips as needed throughout the day. Use as overnight treatment for intensive repair.', '/hydrating-lip-treatment-tube.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Brightening Under-Eye Patches', 'Hydrogel under-eye patches infused with brightening ingredients that reduce dark circles and puffiness in just 20 minutes.', '60 patches', 45.00, 'Eye Care', ARRAY['Reduces dark circles', 'Anti-puffiness', 'Instant results'], 'Vitamin C, Caffeine, Niacinamide, Collagen', 'Apply to clean under-eye area. Leave for 20 minutes, then remove and pat remaining essence.', '/brightening-under-eye-patches.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Pore Minimizing Toner', 'Astringent toner that tightens pores, controls oil production, and refines skin texture for a smoother appearance.', '200ml', 35.00, 'Toners', ARRAY['Pore minimizing', 'Oil control', 'Texture refining'], 'Witch Hazel, Niacinamide, Salicylic Acid', 'Apply to clean face with cotton pad, focusing on T-zone. Use morning and evening.', '/pore-minimizing-toner-bottle.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Anti-Aging Hand Cream', 'Rich hand cream with anti-aging ingredients that protects, repairs, and maintains youthful-looking hands and cuticles.', '75ml', 32.00, 'Hand Care', ARRAY['Hand protection', 'Anti-aging', 'Cuticle care'], 'Retinol, Vitamin C, Shea Butter, SPF 15', 'Massage into hands and cuticles as needed. Reapply after washing hands.', '/anti-aging-hand-cream-tube.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Detoxifying Charcoal Cleanser', 'Deep-cleansing charcoal cleanser that removes toxins, excess oil, and impurities while maintaining skin balance.', '150ml', 38.00, 'Cleansers', ARRAY['Detoxifying', 'Deep cleansing', 'Oil control'], 'Activated Charcoal, Salicylic Acid, Tea Tree Oil', 'Massage onto wet face, work into lather, then rinse thoroughly. Use 2-3 times per week.', '/detoxifying-charcoal-cleanser.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Rosewater Hydrating Mist', 'Pure rosewater mist that hydrates, soothes, and refreshes skin while providing a delicate floral fragrance.', '150ml', 24.00, 'Mists', ARRAY['Hydrating', 'Soothing', 'Refreshing'], 'Pure Rose Water, Glycerin, Vitamin E', 'Spray evenly on face and body. Can be used throughout the day for instant refreshment.', '/rosewater-hydrating-mist-spray.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Intensive Foot Cream', 'Rich, therapeutic foot cream that softens rough skin, heals cracks, and provides long-lasting moisture for healthy feet.', '100ml', 28.00, 'Foot Care', ARRAY['Softening', 'Healing', 'Long-lasting moisture'], 'Urea, Shea Butter, Peppermint Oil, Vitamin E', 'Massage into clean feet, focusing on dry areas. Use daily, preferably before bedtime.', '/intensive-foot-cream-tube.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Vitamin E Nourishing Oil', 'Pure vitamin E oil that nourishes, protects, and repairs skin while providing antioxidant benefits for face and body.', '50ml', 35.00, 'Oils', ARRAY['Nourishing', 'Antioxidant protection', 'Skin repair'], 'Vitamin E, Jojoba Oil, Argan Oil, Rosehip Oil', 'Apply few drops to clean skin and massage gently. Can be used alone or mixed with moisturizer.', '/vitamin-e-nourishing-oil-bottle.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Exfoliating Body Scrub', 'Invigorating body scrub with natural exfoliants that removes dead skin cells and leaves skin smooth, soft, and glowing.', '200ml', 42.00, 'Body Care', ARRAY['Body exfoliation', 'Smoothing', 'Glowing skin'], 'Sea Salt, Sugar, Coconut Oil, Vitamin E', 'Massage onto damp skin in circular motions, then rinse thoroughly. Use 2-3 times per week.', '/exfoliating-body-scrub-jar.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Calming Chamomile Cleanser', 'Gentle, calming cleanser with chamomile extract that soothes sensitive skin while effectively removing impurities.', '150ml', 32.00, 'Cleansers', ARRAY['Gentle cleansing', 'Calming', 'Sensitive skin'], 'Chamomile Extract, Aloe Vera, Glycerin', 'Massage onto wet face, work into gentle lather, then rinse with lukewarm water. Use twice daily.', '/calming-chamomile-cleanser-bottle.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Rejuvenating Face Oil', 'Luxurious face oil blend that rejuvenates, nourishes, and restores radiance to mature or dry skin types.', '30ml', 68.00, 'Oils', ARRAY['Rejuvenating', 'Nourishing', 'Radiance'], 'Argan Oil, Rosehip Oil, Vitamin C, Squalane', 'Apply 3-4 drops to clean face and neck. Massage gently until absorbed. Use evening or as needed.', '/rejuvenating-face-oil-bottle.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Mattifying Primer', 'Oil-controlling primer that creates a smooth base for makeup while minimizing pores and controlling shine all day.', '30ml', 38.00, 'Primers', ARRAY['Oil control', 'Pore minimizing', 'Makeup base'], 'Silica, Niacinamide, Zinc Oxide', 'Apply thin layer to clean face before makeup application. Focus on T-zone and areas prone to oiliness.', '/mattifying-primer-tube.jpg', true, NOW(), NOW()),

(gen_random_uuid(), 'Overnight Recovery Mask', 'Intensive overnight mask that works while you sleep to repair, hydrate, and rejuvenate skin for a refreshed morning complexion.', '75ml', 58.00, 'Masks', ARRAY['Overnight repair', 'Intensive hydration', 'Rejuvenating'], 'Hyaluronic Acid, Peptides, Ceramides, Vitamin B5', 'Apply generous layer to clean face before bed. Leave on overnight, rinse in morning if desired.', '/overnight-recovery-mask-jar.jpg', true, NOW(), NOW());
